# -*- coding: utf-8 -*-
import json
with open('scripts/socio_ch1234.json','r',encoding='utf-8') as f: base=json.load(f)
final_exam=[
{"question":"Selon Bourdieu, qu'est-ce qui distingue fondamentalement le capital culturel institutionnalisé du capital culturel incorporé ?","choices":["L'un est hérité, l'autre acquis par effort","L'incorporé est intégré dans les dispositions durables (manières d'être, goûts), l'institutionnalisé est objectivé sous forme de diplômes reconnus socialement","L'institutionnalisé est plus valorisé dans tous les champs","L'incorporé est mesurable, l'institutionnalisé ne l'est pas"],"correct_index":1,"explanation":"Capital incorporé = dans le corps et les dispositions (habitus). Capital institutionnalisé = le diplôme, titre officiellement reconnu."},
{"question":"Pourquoi l'autonomisation du champ artistique n'est-elle ni linéaire ni irréversible selon Bourdieu ?","choices":["Les artistes reviennent toujours à dépendre de l'État","Elle reste menacée par les forces hétéronomes (marché, État, commande) et dépend de l'évolution des codes mentaux collectifs","Le marché finit toujours par dominer tous les champs","Les artistes choisissent parfois d'y renoncer volontairement"],"correct_index":1,"explanation":"L'autonomisation est fragile : les forces hétéronomes exercent une pression permanente pour réintroduire leurs logiques dans le champ."},
{"question":"Qu'est-ce que le nomos et pourquoi est-il central pour comprendre les champs culturels ?","choices":["Une loi juridique régissant les droits d'auteur","Le principe de fonctionnement des champs culturels : rejet ostensible de la logique marchande, qui produit de la valeur symbolique par la dénégation de la valeur économique","Le nom du sous-champ des avant-gardes","Un concept ethnologique de Mauss repris par Bourdieu"],"correct_index":1,"explanation":"Le nomos : en rejetant la logique marchande, les acteurs produisent de la valeur symbolique — c'est le mode de régulation propre des champs culturels."},
{"question":"Comment l'économie de la mauvaise foi articule-t-elle sincérité et stratégie ?","choices":["Les acteurs sont cyniques et hypocrites","Le désintéressement n'est ni pure sincérité ni pure hypocrisie : c'est une stratégie incorporée — jouer sincèrement le nomos tout en maximisant le capital symbolique à long terme","Les acteurs calculent froidement leur intérêt","L'économie de la mauvaise foi s'applique uniquement aux éditeurs"],"correct_index":1,"explanation":"L'acteur se comporte sincèrement comme désintéressé (le nomos l'y oblige) mais produit ce faisant un investissement symbolique rentable à terme."},
{"question":"Selon Becker, pourquoi la déviance n'est-elle pas une propriété de l'acte lui-même ?","choices":["Parce que tous les actes sont relatifs","Parce que la déviance est le résultat d'un étiquetage social : 'un acte déviant, c'est un acte que d'autres ont réussi à faire étiqueter ainsi'","Parce que la déviance est définie par la loi","Parce que la déviance est culturellement relative selon les pays"],"correct_index":1,"explanation":"La déviance n'est pas dans l'acte mais dans l'étiquette posée par ceux qui ont le pouvoir de nommer."},
{"question":"Comment Becker définit-il un 'monde de l'art' ?","choices":["L'ensemble des institutions culturelles subventionnées","Ensemble de personnes dont l'activité coopérative, organisée autour de conventions partagées, produit des oeuvres d'art","Le champ autonome au sens de Bourdieu","Le marché de l'art international"],"correct_index":1,"explanation":"Monde de l'art = réseau de coopération organisé autour de conventions."},
{"question":"Quel est le double rôle des conventions selon Becker ?","choices":["Elles protègent les droits et régulent les marchés","Elles facilitent la coopération (tout le monde sait quoi faire) ET contraignent la création (s'en écarter risque de ne pas être compris ou accepté)","Elles définissent le beau et excluent le laid","Elles distinguent art légitime et populaire"],"correct_index":1,"explanation":"Conventions : facilitent la coordination mais contraignent simultanément la liberté créatrice."},
{"question":"Comment la frontière entre déviance artistique et révolution artistique est-elle déterminée selon Becker ?","choices":["Par le talent objectif de l'artiste","Par un processus social : si l'artiste transgressif convainc les membres du monde de l'art de valider sa démarche, la déviance devient révolution","Par le marché et le succès commercial","Par les institutions académiques uniquement"],"correct_index":1,"explanation":"La valeur artistique est une construction sociale : la déviance devient révolution quand le monde de l'art la valide."},
{"question":"Quelle est la différence fondamentale entre l'approche de Bourdieu et celle de Becker sur la production artistique ?","choices":["Bourdieu étudie la peinture, Becker la musique","Bourdieu analyse les structures de domination (positions, capitaux, luttes), Becker les processus de coopération (conventions, interactions) — l'un regarde vertical, l'autre horizontal","Bourdieu est quantitatif, Becker qualitatif","Becker reconnaît la valeur esthétique, Bourdieu non"],"correct_index":1,"explanation":"Bourdieu (vertical, domination, structure) vs Becker (horizontal, coopération, interactions)."},
{"question":"Qu'est-ce que la patrimonialisation et pourquoi est-elle toujours conflictuelle ?","choices":["C'est la gestion financière des biens publics","C'est le processus par lequel des biens sont désignés comme méritant d'être transmis — conflictuel parce qu'il engage des luttes sur quelle mémoire est collective et légitime","C'est uniquement le travail des conservateurs de musées","C'est un processus neutre et technique"],"correct_index":1,"explanation":"Patrimonialiser = choisir quelle mémoire transmettre. Un acte politique qui engage des rapports de pouvoir."},
{"question":"En quoi l'extension au patrimoine immatériel (UNESCO 2003) transforme-t-elle la notion de culture ?","choices":["Elle ne change rien à la notion","Elle l'élargit à des pratiques vivantes, ordinaires, non monumentales — rapprochant la notion de culture du sens anthropologique et s'éloignant de la vision normative fondée sur les beaux-arts","Elle réduit la notion de culture aux pratiques folkloriques","Elle privatise la gestion du patrimoine"],"correct_index":1,"explanation":"Du monument au vivant : patrimonialiser les pratiques immatérielles, c'est adopter une vision anthropologique de la culture."},
{"question":"Pourquoi la littérarité n'est-elle pas une propriété intrinsèque d'un texte ?","choices":["Parce que les textes ne parlent pas d'eux-mêmes","Parce qu'elle est construite par des institutions (prix, programmes scolaires, éditeurs) et des intermédiaires culturels — elle varie selon les époques et les rapports de forces","Parce que la définition du littéraire est subjective","Parce que les auteurs décident eux-mêmes si leur texte est littéraire"],"correct_index":1,"explanation":"La littérarité est une valeur socialement construite et institutionnellement produite."},
{"question":"Comment la notion de violence symbolique permet-elle d'analyser la patrimonialisation ?","choices":["Elle prouve que la patrimonialisation est violente physiquement","En désignant certains biens comme 'le' patrimoine collectif, les acteurs dominants imposent une vision du passé que les dominés intériorisent comme légitime — sans voir que c'est une construction","La violence symbolique ne s'applique pas au patrimoine","Elle explique uniquement les conflits armés autour des monuments"],"correct_index":1,"explanation":"La patrimonialisation impose une mémoire légitime en occultant sa nature de construction sociale."},
{"question":"Pourquoi la trivialité n'est-elle pas une propriété des oeuvres ?","choices":["Parce que toutes les oeuvres se valent","Parce que c'est une étiquette posée par ceux qui ont le pouvoir de définir la valeur — la frontière trivial/légitime est historiquement mouvante et reflète des rapports de forces","Parce que la trivialité est définie par le marché","Parce que le public ne voit pas la différence"],"correct_index":1,"explanation":"Trivialité = étiquette sociale. Molière était trivial, le roman policier a longtemps été exclu du canon — la frontière change."},
{"question":"Comment l'interactionnisme symbolique de Becker se distingue-t-il du structuralisme de Bourdieu ?","choices":["L'interactionnisme rejette toute analyse des structures","L'interactionnisme : l'ordre social est co-produit dans les interactions quotidiennes (bottom-up). Le structuralisme : les structures préexistent et orientent les pratiques (top-down)","Le structuralisme est plus récent","L'interactionnisme est une variante du structuralisme"],"correct_index":1,"explanation":"Interactionnisme : ordre produit par les interactions. Structuralisme : structures qui orientent les pratiques. Deux angles complémentaires."},
{"question":"Qu'est-ce que l'auto-élimination et pourquoi est-elle un mécanisme de reproduction sociale ?","choices":["Une stratégie délibérée d'exclusion","Les personnes éloignées des codes culturels légitimes se disent 'ce n'est pas pour moi' sans interdiction explicite — la domination est intériorisée, contribuant à reproduire les inégalités sans contrainte visible","Un phénomène individuel sans portée sociale","Un mécanisme propre aux classes supérieures"],"correct_index":1,"explanation":"L'auto-élimination = intériorisation de l'exclusion. Les dominés contribuent à leur propre domination — mécanisme central de la reproduction sociale."},
{"question":"Selon Dubois, quelle vision de la sociologie de la culture est aujourd'hui dominante ?","choices":["La vision thématique, centrée sur la sociologie de l'art","La vision conceptuelle / transversale : la culture comme point d'entrée pour comprendre les rapports sociaux dans leur ensemble","La vision économique de la culture","La vision esthétique héritée de la philosophie de l'art"],"correct_index":1,"explanation":"La vision conceptuelle fait de la culture un prisme analytique transversal — non plus un secteur délimité."},
{"question":"Pourquoi l'analyse de L'Amour de l'art (Bourdieu, 1966) dépasse-t-elle une simple description statistique des visiteurs de musées ?","choices":["Parce qu'elle porte sur 10 000 personnes","Parce qu'elle transforme les inégalités d'accès en analyse de mécanisme de reproduction sociale — le diplôme révèle que les inégalités culturelles sont des inégalités sociales intériorisées","Parce qu'elle compare plusieurs pays","Parce qu'elle inclut des données qualitatives"],"correct_index":1,"explanation":"Bourdieu transforme un constat statistique en mécanisme sociologique : les inégalités culturelles reproduisent les inégalités sociales."},
{"question":"Comment les conventions beckerien articulent-elles liberté artistique et contrainte sociale ?","choices":["Elles éliminent la liberté artistique","Toute création se situe dans un rapport aux conventions : même la transgression est définie par rapport à elles — la liberté est un positionnement relatif, non un absolu","Les conventions n'empêchent pas la liberté","Les artistes peuvent ignorer les conventions sans conséquence"],"correct_index":1,"explanation":"Même la transgression la plus radicale se définit par rapport aux conventions transgressées."},
{"question":"Pourquoi peut-on dire que la classification culturelle est un acte performatif ?","choices":["Parce qu'elle est spectaculaire et publique","Parce qu'en nommant quelque chose 'patrimoine', 'littéraire' ou 'trivial', on ne décrit pas une réalité préexistante — on la produit. La classification crée la réalité qu'elle est censée décrire","Parce qu'elle a des effets financiers immédiats","Parce qu'elle implique toujours une performance artistique"],"correct_index":1,"explanation":"Performatif : dire 'c'est un monument historique' produit un monument historique. Le langage crée le monde social."},
{"question":"Comment articuler Bourdieu et Becker pour analyser les inégalités culturelles ?","choices":["Ils sont incompatibles","Bourdieu fournit les structures (champs, capitaux, domination) qui distribuent inégalement les ressources. Becker permet d'analyser comment, concrètement, les conventions et les interactions reproduisent ou contestent ces inégalités","Becker s'intéresse aux inégalités, Bourdieu non","Il faut choisir entre les deux"],"correct_index":1,"explanation":"Les deux approches sont complémentaires : Bourdieu (structure) + Becker (processus) = analyse plus complète des inégalités."},
{"question":"Qu'est-ce qu'un bien symbolique et en quoi dépasse-t-il la frontière culture légitime/populaire ?","choices":["Un bien dont la valeur dépend du marché","Un objet qui tire sa valeur de sa signification — en incluant les pratiques populaires et numériques dans ce spectre, la notion permet une analyse non normative avec les mêmes outils pour une oeuvre classique et un mème","Un bien produit dans le pôle de production restreinte","Un bien subventionné par l'État"],"correct_index":1,"explanation":"Le bien symbolique : valeur par signification (non utilité). Permet d'analyser le hip-hop ou un mème avec les mêmes outils qu'une symphonie."},
{"question":"Pourquoi le risque de folklorisation est-il inhérent à la patrimonialisation ?","choices":["Parce que les musées sont mal gérés","En figeant des pratiques vivantes dans un cadre institutionnel pour les transmettre, on risque de les vider de leur sens et de leur dynamisme — transformer le vivant en objet muséifié","Parce que les experts manquent de formation","Parce que le financement public impose des contraintes"],"correct_index":1,"explanation":"Le paradoxe du patrimoine immatériel : figer pour transmettre risque de détruire ce qui en fait la valeur."},
{"question":"Comment la sociologie de la culture renouvelle-t-elle la question du génie artistique ?","choices":["Elle prouve que le génie existe objectivement","En substituant à la figure du génie isolé celle de la production collective : l'oeuvre résulte de conditions sociales (Bourdieu : champ) et de coopérations organisées (Becker : conventions). Le génie est une construction sociale","Elle nie l'existence du talent individuel","Elle ne s'intéresse pas au génie"],"correct_index":1,"explanation":"Bourdieu + Becker : le génie est une construction sociale produite par le champ et les mondes de l'art."},
{"question":"En quoi la notion de capital symbolique permet-elle de penser des formes de domination non visibles ?","choices":["Le capital symbolique est plus visible que le capital économique","La domination symbolique est d'autant plus efficace qu'elle est méconnue : les dominés la vivent comme légitime. Les ressources symboliques (prestige, réputation) structurent des rapports de domination aussi réels que l'argent","Le capital symbolique n'a aucun effet de domination","Il s'applique uniquement au champ artistique"],"correct_index":1,"explanation":"Violence symbolique : domination méconnue comme telle — les dominés participent à leur propre domination en intériorisant les catégories des dominants."},
{"question":"Comment les trois auteurs (Dubois, Bourdieu, Becker) s'articulent-ils pour comprendre la sociologie de la culture ?","choices":["Ils sont en contradiction totale","Dubois fournit le cadre disciplinaire (culture = point d'entrée des rapports sociaux, biens symboliques). Bourdieu analyse les structures de domination (champ, capitaux). Becker les processus de coopération (conventions, mondes de l'art)","Un seul auteur suffit","Dubois synthétise Bourdieu et Becker"],"correct_index":1,"explanation":"Les trois s'articulent : cadre disciplinaire (Dubois) + structures (Bourdieu) + processus (Becker)."},
{"question":"Pourquoi l'évolution sémantique du mot culture est-elle une entrée analytique pour la sociologie ?","choices":["Elle montre que la définition est stable","Les glissements sémantiques (latin/XVIe/XIXe siècle) révèlent des rapports de pouvoir : le mot sert à hiérarchiser, à légitimer des dominations. Analyser l'histoire du mot, c'est analyser l'histoire des rapports sociaux","Elle prouve que la culture est universelle","Elle illustre l'évolution linguistique"],"correct_index":1,"explanation":"L'histoire du mot culture = histoire des luttes pour définir ce qui mérite d'être considéré comme culture."},
{"question":"En quoi la distinction pôle restreint/grande production n'est-elle pas un jugement de valeur ?","choices":["C'est effectivement un jugement de valeur implicite","Bourdieu analyse deux logiques de légitimation coexistantes dans le champ — l'une par les pairs (prestige), l'autre par le marché (succès). Ce sont deux économies symboliques différentes, non une hiérarchie morale","Le pôle restreint est objectivement supérieur","La grande production est exclusivement commerciale"],"correct_index":1,"explanation":"Pôle restreint vs grande production = deux logiques de légitimation, non une hiérarchie normative."},
{"question":"Comment la notion de 'frontière' est-elle centrale pour la sociologie de la classification ?","choices":["Les frontières culturelles sont des données naturelles","Les frontières (littéraire/trivial, patrimoine/déchet) sont des constructions sociales mouvantes produites par des acteurs situés — analyser les frontières, c'est analyser les rapports de pouvoir qui les produisent","Les frontières sont définies uniquement par les marchés","Les frontières culturelles ne changent pas"],"correct_index":1,"explanation":"Analyser les frontières = analyser le travail social de classification et les rapports de pouvoir qui les sous-tendent."},
{"question":"En quoi l'interactionnisme symbolique complète-t-il l'analyse bourdieusienne pour penser la production culturelle ?","choices":["Il la contredit entièrement","Bourdieu rend visibles les structures de domination mais peut être accusé de déterminisme. Becker complète en montrant comment les acteurs négocient, coopèrent et contestent concrètement — le changement est possible","L'interactionnisme est moins rigoureux","Becker ignore les inégalités"],"correct_index":1,"explanation":"Bourdieu + Becker : structures de domination + capacité d'action et de négociation des acteurs. Dépasse le déterminisme sans tomber dans l'idéalisme."},
{"question":"Pourquoi la sociologie de la culture doit-elle être réflexive sur ses propres catégories ?","choices":["Pour des raisons éthiques uniquement","Parce que le sociologue n'échappe pas aux classifications dominantes — analyser la 'culture légitime' sans objectiver cette catégorie, c'est la reproduire. La réflexivité est une condition de la rigueur scientifique","La réflexivité est optionnelle en sociologie","Pour plaire à tous les acteurs du champ"],"correct_index":1,"explanation":"Réflexivité : le sociologue doit objectiver sa propre position et ses propres catégories — condition sine qua non de la sociologie critique."}
]
base['final_exam']=final_exam
with open('scripts/sociologie.json','w',encoding='utf-8') as f: json.dump(base,f,ensure_ascii=False,indent=2)
print(f'DONE — sociologie.json : {len(json.dumps(base))} chars, {len(base["chapters"])} chapitres, {len(final_exam)} questions examen blanc')
