import json, os

# Charger les 6 chapitres déjà générés
chapters = []
for i in range(1, 7):
    path = f'/home/claude/intern_ch{i}.json'
    with open(path, 'r', encoding='utf-8') as f:
        chapters.append(json.load(f))

# Examen blanc — 30 questions difficiles piochées dans les chapitres
final_exam = [
  # Ch1
  {"question": "Quel pourcentage des films projetés en Europe venait des USA en 1919 ?", "choices": ["50%","75%","90%","100%"], "correct_index": 2, "explanation": "En 1919, 90% des films projetés en Europe venaient des États-Unis. La domination française s'est effondrée après la Première Guerre mondiale."},
  {"question": "Qu'est-ce que l'intégration verticale dans l'industrie cinématographique ?", "choices": ["Produire des films dans plusieurs pays","Le contrôle par une même entreprise de la production, la distribution et l'exploitation","Faire travailler des acteurs internationaux","Vendre les droits à l'étranger"], "correct_index": 1, "explanation": "L'intégration verticale = contrôle de l'ensemble de la filière de l'amont (production) vers l'aval (exploitation des salles)."},
  {"question": "Qu'est-ce que le block booking ?", "choices": ["Réservation de salles à l'avance","Lier la vente d'un film à succès à l'achat de nombreux films médiocres","Vente d'un film avant sa réalisation","Un accord entre distributeurs américains"], "correct_index": 1, "explanation": "Le block booking forçait les exploitants à acheter des films médiocres (jusqu'à 104 mauvais pour 1 bon) s'ils voulaient accéder aux films à succès."},
  {"question": "Pourquoi le gouvernement américain soutient-il l'exportation des films hollywoodiens ?", "choices": ["Le gouvernement est propriétaire des studios","Les films sont des vitrines du mode de vie américain et favorisent les exportations commerciales — soft power + impact sur les ventes","Les studios paient des impôts très élevés","Hollywood finance les campagnes électorales"], "correct_index": 1, "explanation": "Deux raisons : soft power (vitrine du mode de vie américain) et impact commercial direct (Hoover : 'Où pénètrent les films américains, on vend deux fois plus d'automobiles américaines')."},
  {"question": "Quel film de 1915 marque le début des superproductions à Hollywood ?", "choices": ["Le Voyage dans la Lune","Le Grand Train de l'Ouest","The Birth of a Nation","Naissance d'une nation"], "correct_index": 2, "explanation": "The Birth of a Nation (Griffith, 1915) coûte 100 000$ et rapporte 20 millions — révélant qu'en investissant massivement on génère des recettes disproportionnées."},
  # Ch2
  {"question": "Qu'est-ce que le divorcment de 1948 ?", "choices": ["Le divorce entre studios et stars","L'obligation pour les majors de se séparer de la production ou de l'exploitation","La séparation des majors et des minors","L'interdiction du block booking"], "correct_index": 1, "explanation": "Le divorcment de 1948 oblige les majors à choisir entre production et exploitation. Toutes choisissent la production, sauf RKO."},
  {"question": "Quel est le résultat paradoxal des Fin-Syn Rules (1970) selon Kerry Seagrave ?", "choices": ["Elles ont rendu les Networks plus puissants","En voulant limiter les Networks, elles ont concentré le pouvoir de distribution internationale entre les mains des majors — 80% des recettes internationales de syndication en 1990","Elles ont favorisé les producteurs indépendants","Elles ont permis à l'État de contrôler la production TV"], "correct_index": 1, "explanation": "En interdisant aux Networks la production et la syndication, les Fin-Syn Rules ont involontairement concentré ces activités entre les mains des majors, renforçant leur domination internationale."},
  {"question": "En quelle année les recettes vidéo des majors dépassent-elles les entrées en salle ?", "choices": ["1980","1983","1986","1990"], "correct_index": 2, "explanation": "Dès 1986, les recettes tirées de la location et vente de cassettes vidéo représentent plus d'argent que les entrées en salle pour les majors hollywoodiennes."},
  {"question": "Qu'est-ce que la syndication dans le marché télévisuel américain ?", "choices": ["Un accord entre producteurs pour partager les droits","Le marché de l'occasion des programmes — diffusé par un Network puis revendu à des stations locales","Un système de financement des séries","La vente de programmes à l'international"], "correct_index": 1, "explanation": "La syndication est le marché de l'occasion : un programme diffusé par un Network peut être revendu à des stations locales. Les Fin-Syn Rules ont interdit aux Networks de gérer ce marché."},
  {"question": "Qu'est-ce qu'un blockbuster et d'où vient ce terme ?", "choices": ["Un film indépendant à petit budget","Une superproduction hollywoodienne — terme militaire (bombe détruisant un pâté de maisons) désignant l'objectif d'écraser la concurrence","Un film produit hors des USA","Un film tourné entièrement en studio"], "correct_index": 1, "explanation": "Le terme militaire désigne une superproduction à très gros budget. Objectif : écraser la concurrence avec les plus grandes stars et les meilleurs effets spéciaux."},
  # Ch3
  {"question": "Quelle est la première mégafusion de l'industrie médiatique mondiale ?", "choices": ["Rachat de Columbia par Sony (1989)","Rachat de Fox par Murdoch (1984)","Rachat de Warner par Time (1989) créant Time Warner","Rachat de Paramount par Gulf Western (1966)"], "correct_index": 2, "explanation": "Le rachat de Warner par Time en 1989, créant Time Warner, est la première mégafusion. Elle annonce celles qui se développent dans les années 1990-2000."},
  {"question": "Qu'est-ce que Napster et quelle est son importance historique ?", "choices": ["Une plateforme légale de VOD créée en 2002","Un réseau pair-à-pair d'échange de fichiers musicaux créé en 1999 par Shawn Fanning — 7 millions d'utilisateurs, fermé en 2001","Un site de vente de DVD en ligne","Un système de streaming créé par Hollywood"], "correct_index": 1, "explanation": "Napster (1999) est la première grande plateforme de partage de fichiers musicaux. 7 millions d'utilisateurs à son pic. Fermé en 2001 après procès de la RIAA."},
  {"question": "Que révèle l'étude de Burgess & Green (2009) sur YouTube ?", "choices": ["YouTube était exclusivement une plateforme de vidéos amateurs","Sur les 4 000 vidéos les plus populaires, plus de la moitié venait des industries culturelles traditionnelles — YouTube était aussi un canal de diffusion professionnelle","Les vidéos amateurs étaient plus vues que les professionnelles","YouTube ne diffusait aucun contenu des industries culturelles"], "correct_index": 1, "explanation": "L'étude montre que sur les 4 000 vidéos les plus populaires, une petite majorité provenait des industries culturelles traditionnelles. YouTube n'était pas qu'une plateforme amateur."},
  {"question": "Quel modèle original Netflix avait-il avant de passer au streaming ?", "choices": ["Un service de streaming dès sa création","La location de DVD par correspondance (1997) — 1 milliard de DVD loués en 2007 avant la migration vers le streaming","Un réseau de salles de cinéma","Un service de câble comme HBO"], "correct_index": 1, "explanation": "Netflix est créé en 1997 comme service de location de DVD par correspondance avec des atouts distinctifs (prix bas, pas de frais de port, recommandations). Il atteint 1 milliard de DVD loués en 2007."},
  {"question": "Qu'est-ce que Hulu et qui le crée en 2008 ?", "choices": ["Une plateforme créée par Netflix pour concurrencer Disney","Une plateforme créée par ABCUniversal proposant un modèle gratuit financé par la publicité — coûts pub 60% inférieurs aux Networks","Un service créé par le gouvernement américain","Une plateforme créée par Sony Pictures"], "correct_index": 1, "explanation": "Hulu (2008) est créé par ABCUniversal avec un modèle gratuit financé par la publicité, alternative légale aux plateformes pirates. Disney en devient actionnaire majoritaire en 2019."},
  # Ch4
  {"question": "Qui est Felix Caignet et quel est son rôle dans l'histoire de la telenovela ?", "choices": ["Fondateur de Televisa au Mexique","Pionnier de la radionovela cubaine — Le droit de naitre (1948, 314 épisodes). Formule : 'Pleurer est un plaisir'","Fondateur de Rede Globo au Brésil","Réalisateur de la première telenovela brésilienne"], "correct_index": 1, "explanation": "Felix Caignet diffuse Le droit de naitre en 1948 sur la radio CMQ. Sa formule 'Pleurer est un plaisir' définit le genre mélodramatique. Le programme s'exporte dès 1948."},
  {"question": "Qu'est-ce que la proximité culturelle selon Joseph Straubhaar ?", "choices": ["Le fait que les cultures proches géographiquement ont les mêmes goûts","Le succès international des telenovelas s'explique par le fait que les publics se sentent plus proches de ces programmes que des programmes américains car ils y voient des réalités moins éloignées","Le fait que seuls les pays hispanophones regardent les telenovelas","La supériorité technique des telenovelas sur les séries américaines"], "correct_index": 1, "explanation": "Straubhaar (fin des années 1970) : les publics préfèrent les telenovelas aux programmes américains parce qu'ils y voient des réalités moins éloignées de leur vécu."},
  {"question": "En quoi la telenovela brésilienne (Globo) est-elle différente de la mexicaine (Televisa) ?", "choices": ["La brésilienne est plus commerciale","La brésilienne est plus proche des réalités sociales et moins manichéenne — des intellectuels critiques se réfugient dans la fiction télévisée sous la dictature militaire","La mexicaine est plus réaliste socialement","Elles sont strictement identiques"], "correct_index": 1, "explanation": "La dictature militaire (1964-1983) pousse des intellectuels critiques vers la fiction télévisée de Globo, y introduisant une dimension sociale plus réaliste. Beto Rockefeller (1968-69) marque ce tournant."},
  {"question": "Qu'est-ce qu'un contre-flux selon Daya Thussu (2007) ?", "choices": ["Des accords entre producteurs pour contourner le droit d'auteur","Des flux médiatiques qui viendraient s'opposer aux flux dominants américains — les telenovelas en seraient emblématiques","La politique anti-piratage des industries culturelles","La domination des programmes américains sur les marchés mondiaux"], "correct_index": 1, "explanation": "Daya Thussu (2007) développe l'idée que les telenovelas sont emblématiques de contre-flux — des flux non américains qui s'opposent aux flux dominants. Mais cette idée a des limites importantes."},
  {"question": "Pourquoi les exportations de telenovelas sont-elles 'économiquement insignifiantes' selon Hesmondhalgh ?", "choices": ["Parce que les telenovelas ne sont jamais exportées","Parce que leur volume ne réussit pas à contrebalancer les flux américains dominants — les contre-flux existent mais restent marginaux économiquement","Parce qu'elles coûtent trop cher à l'export","Parce que les droits de diffusion sont trop compliqués"], "correct_index": 1, "explanation": "Hesmondhalgh reconnaît l'existence des exportations mais relativise : leur volume ne contrebalance pas les flux américains. Les contre-flux sont réels mais asymétriques."},
  # Ch5
  {"question": "Qu'est-ce que le cinéma masala ?", "choices": ["Un film de Bollywood tourné en anglais","Un film qui concentre tous les genres (action, romance, musique, danse, policier) pour toucher le maximum de spectateurs — né de l'atomisation de la production dans les années 1940","Un genre de films d'horreur indien","Un style réaliste inspiré du néoréalisme européen"], "correct_index": 1, "explanation": "Le cinéma masala (mélange d'épices) concentre tous les genres en un seul film pour toucher tout le public indien — une réponse à l'atomisation de la production."},
  {"question": "Quelle thèse Adrian Athique défend-il sur le piratage du cinéma indien ?", "choices": ["Le piratage a totalement détruit le cinéma indien","Sans les pirates, il aurait été difficile de développer dans les années 1980 les marchés d'exportation des films indiens — le piratage a joué un rôle de distributeur dans les marchés non servis","Le piratage n'a eu aucun impact sur le cinéma indien","Le piratage a uniquement nui aux producteurs indiens"], "correct_index": 1, "explanation": "Athique (India Media) montre que le piratage a assuré la distribution des films indiens dans des marchés (diaspora, Golfe, Afrique) que les circuits officiels ne servaient pas."},
  {"question": "Pourquoi le cinéma indien a-t-il recouru à l'argent sale pour son financement jusqu'en 1998 ?", "choices": ["Parce que les producteurs indiens étaient corrompus","Parce que l'État indien refusait de reconnaître le cinéma comme industrie légitime (jusqu'en 1998), l'empêchant d'accéder aux prêts bancaires intéressants","Parce que les recettes des films étaient insuffisantes","Parce que les banques indiennes refusaient tout prêt culturel"], "correct_index": 1, "explanation": "Sans statut d'industrie légitime, le cinéma indien ne pouvait pas accéder aux prêts bancaires normaux. Il a dû se tourner vers des investisseurs aux sources douteuses pour financer les productions."},
  {"question": "Qu'est-ce que Zee TV et quel impact a-t-il eu sur l'audiovisuel indien ?", "choices": ["Un studio de cinéma bollywoodien","Une chaîne satellite créée en 1992 par Subhash Chandra — première à proposer des programmes indiens à l'échelle de l'Asie. Elle représente 65% du marché câble/satellite en Inde et démontre la nécessité d'une stratégie de localisation","La première chaîne publique indienne","Un service de streaming créé par Netflix en Inde"], "correct_index": 1, "explanation": "Zee TV (1992) est la première chaîne satellite à miser sur les programmes locaux indiens. Elle représente 65% du marché câble/satellite en Inde et impose la leçon : pour dominer le marché indien, il faut des contenus locaux."},
  {"question": "Pourquoi la diaspora indienne représente-t-elle 75% des recettes internationales du cinéma indien ?", "choices": ["Parce qu'elle est la seule à avoir accès aux films indiens","Parce qu'elle représente 20M+ personnes avec un revenu supérieur aux Indiens restés au pays, et utilise les films pour maintenir un lien culturel avec le pays d'origine — un marché premium fortement motivé","Parce que les films indiens ne sont pas distribués dans les autres pays","Parce que la diaspora achète uniquement des DVD"], "correct_index": 1, "explanation": "La diaspora (20M+ personnes, revenu supérieur) utilise les films indiens comme support identitaire. C'est un marché premium fortement motivé qui explique les 75% des recettes internationales."},
  # Ch6
  {"question": "Qu'est-ce que le trendy drama japonais ?", "choices": ["Un drama historique japonais","Un genre créé par Ota Toru : beaux acteurs (vingtaine d'ans), lieux branchés de Tokyo, tenues à la mode, romance et tubes musicaux. Package : casting > musique > scénario","Un drama policier japonais","Un genre de séries d'animation japonaise"], "correct_index": 1, "explanation": "Le trendy drama d'Ota Toru (Fuji TV) cible les 20-30 ans avec un package de succès précis : casting en premier (stars réservées 2 ans à l'avance), puis musique, puis scénario."},
  {"question": "Qu'est-ce que la Hallyu ?", "choices": ["La domination américaine du cinéma coréen","La vague coréenne — le succès international des produits de la culture populaire sud-coréenne, notamment les K-Dramas","Un mouvement de censure du cinéma coréen","Le nom du système de production des dramas japonais"], "correct_index": 1, "explanation": "Hallyu désigne la vague coréenne, c'est-à-dire le succès international des K-Dramas et plus largement de la culture populaire sud-coréenne depuis les années 1990."},
  {"question": "Quel facteur économique explique principalement l'essor des dramas coréens au détriment des japonais à partir de 1998 ?", "choices": ["La meilleure qualité artistique des dramas coréens","Le prix : 1 200$ l'épisode coréen vs 8 000$ pour le japonais à Taïwan. La crise asiatique de 1998 pousse les chaînes vers les dramas coréens moins chers","L'interdiction des dramas japonais en Asie","La supériorité technologique des studios coréens"], "correct_index": 1, "explanation": "Le différentiel de prix (1 200$ vs 8 000$) combiné à la crise asiatique de 1998 explique le basculement des chaînes asiatiques vers les dramas coréens."},
  {"question": "Qu'est-ce que DramaFever et que révèle son rachat par Warner en 2016 ?", "choices": ["Une chaîne coréenne rachetée par Warner","Une plateforme de diffusion légale de dramas coréens aux USA (2009) rachetée par Warner — révélant que les grands groupes hollywoodiens reconnaissent la valeur des dramas coréens et veulent contrôler leur distribution","Un fonds d'investissement dans les médias coréens","Un festival de séries asiatiques aux USA"], "correct_index": 1, "explanation": "DramaFever (2009) est racheté par Warner en 2016 — Hollywood reconnaît la valeur commerciale des dramas coréens et reprend le contrôle de leur distribution légale aux USA."},
  {"question": "Quel est le volume des exportations audiovisuelles coréennes en 2011 et que révèle ce chiffre ?", "choices": ["5 milliards de dollars — la Corée domine les échanges mondiaux","252 millions de dollars — soit la moitié de ce que rapporte un grand film américain, illustrant à la fois le succès de la Hallyu et l'asymétrie structurelle persistante face aux flux américains","10 milliards de dollars — dépassant Hollywood","50 millions de dollars — un succès trop marginal pour être significatif"], "correct_index": 1, "explanation": "252 millions de dollars illustre la Hallyu (flux non américains significatifs) ET l'asymétrie persistante (ce total correspond à la moitié d'un seul grand film américain)."}
]

data = {
  "subject_name": "Internationalisation des programmes de fiction",
  "teacher_name": "Sophie Noël",
  "subject_color": "mint",
  "icon": "film",
  "exam_type": "qrc",
  "next_exam": "11 mai 2025",
  "chapters": chapters,
  "final_exam": final_exam
}

output = '/home/claude/internationalisation.json'
with open(output, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Validation finale
with open(output, 'r') as f:
    loaded = json.load(f)

print(f"\n=== VALIDATION FINALE ===")
print(f"Matière : {loaded['subject_name']}")
print(f"Chapitres : {len(loaded['chapters'])}")
for ch in loaded['chapters']:
    fc = len(ch['flashcards'])
    easy = len(ch['qcm']['easy'])
    med = len(ch['qcm']['medium'])
    hard = len(ch['qcm']['hard'])
    qrc = len(ch['qrc'])
    panic = len(ch['panic'])
    print(f"  Ch{ch['number']} — {ch['title'][:45]} | FC:{fc} | QCM:{easy}/{med}/{hard} | QRC:{qrc} | Panic:{panic}")
print(f"Examen blanc : {len(loaded['final_exam'])} questions")
size_mb = os.path.getsize(output) / 1024 / 1024
print(f"Taille du fichier : {size_mb:.2f} MB")
print(f"=========================")